export const CONFIG = {
  email: "senator.x.x85@gmail.com",
  askTitle: "با من میای سر قرار نرگس خانم ؟",
  askSub: "نه نداریم ها. امتحان کن 😏",
  noLabel: "نه نداریم ها",
  yesLabel: "آره 💙",
  askHint: "امتحان کن... ولی این دکمه فراره ☁️",
  dateTitle: "کی وقتت آزاده قشنگ؟",
  dateSub: "یه تاریخ و ساعت بده که بدونم کی ببینم دختر قشنگمو 👀",
  dateNext: "خب اینم شد ⭐",
  foodTitle: "شکم کوچولوت چی می‌خواد؟",
  foodSub: "مهمون منی، راحت انتخاب کن 😋",
  foodNext: "بریم که بریم 💌",
  confirmTitle: "دیدی آخرش گفتی آره 😌",
  confirmFooter:
    "این وب‌سایت برای نرگس جونمه و فقط برای تو ساختم. لطفا به کسی نشونش نده و خودت هم نگهش دار😉💙",
  pickupText: "پس آماده باش، خودم میام دنبالت 🚗💨",
  letterKicker: "یه نامه مخصوص خودت",
  letterCaptionWrite: "قلم رفت روی کاغذ ..",
  letterCaptionFold: "داره نامه تا میشه...",
  letterCaptionInsert: "رفته تو پاکت...",
  letterCaptionClose: "در پاکت داره بسته میشه...",
  letterCaptionWax: "موم داغ... یه کم صبر کن",
  letterCaptionDone: "مهر و موم شد 💌",
  letterGreeting: "نرگس خانم،",
  letterSign: "با عشق، محمدحسین",
  skipLetter: "بپر جلو ✨",
  foodCategories: [
    { id: "food", title: "خوراکی" },
    { id: "diet", title: "رژیمی" },
  ],
  foods: [
    { id: "pizza", name: "پیتزا", emoji: "🍕", category: "food" },
    { id: "berger", name: "برگر", emoji: "🍔", category: "food" },
    { id: "sandwich", name: "ساندویچ", emoji: "🥪", category: "food" },
    { id: "pasta", name: "پاستا", emoji: "🍝", category: "food" },
    { id: "kubideh", name: "کوبیده", emoji: "🫔", category: "food" },
    { id: "shishlik", name: "شیشلیک", emoji: "🍖", category: "food" },
    { id: "nachos", name: "ناچوز", emoji: "🧀", category: "food" },
    { id: "eskimo", name: "اسکیمو", emoji: "🍦", category: "food" },
    { id: "ice_cream", name: "بستنی", emoji: "🍨", category: "food" },
    { id: "waffle", name: "وافل", emoji: "🧇", category: "food" },
    { id: "crepe", name: "کرپ", emoji: "🥞", category: "food" },
    { id: "croissant", name: "کروسان بستنی", emoji: "🥐", category: "food" },
    { id: "chocolate", name: "شکلات", emoji: "🍫", category: "food" },
    { id: "shole", name: "شله", emoji: "🍲", category: "food" },
    { id: "maize", name: "بلال", emoji: "🌽", category: "food" },
    { id: "baklava", name: "باقلوا", emoji: "🍮", category: "food" },
    { id: "coffee", name: "قهوه", emoji: "☕", category: "diet" },
    { id: "tea", name: "چای", emoji: "🍵", category: "diet" },
    { id: "juice", name: "آب‌میوه", emoji: "🍹", category: "diet" },
    { id: "yogurt_ice", name: "ماست بستنی", emoji: "🍧", category: "diet" },
    { id: "maize_kebab", name: "بلال کبابی", emoji: "🌽", category: "diet" },
    { id: "chicken", name: "مرغ", emoji: "🐔", category: "diet" },
  ],
};

export const MONTHS = [
  "فروردین",
  "اردیبهشت",
  "خرداد",
  "تیر",
  "مرداد",
  "شهریور",
  "مهر",
  "آبان",
  "آذر",
  "دی",
  "بهمن",
  "اسفند",
];

export const WEEKDAYS = [
  "یکشنبه",
  "دوشنبه",
  "سه‌شنبه",
  "چهارشنبه",
  "پنجشنبه",
  "جمعه",
  "شنبه",
];

export const CLICK_EMOJIS = ["☁️", "🌤️", "💙", "🩵", "✨", "🕊️", "💎", "🌊"];

export const NO_TEASES = [
  "نه نداریم ها",
  "امتحان کن 😌",
  "نرسیدی؟",
  "باز فرار کردم",
  "آره رو بزن دیگه",
];
